name: Lint GitHub Actions Workflows
on:
  push:
    paths:
    - '.github/workflows/**'
jobs:
  actionlint:
    # using `main` as the ref will keep your workflow up-to-date
    uses: hashicorp/vault-workflows-common/.github/workflows/actionlint.yaml@main

self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
    - custom-linux-large